title: Open Seizure Detector
description: Free, Open Source tools to Alert Carers if someone suffers an Epileptic Seizure
show_downloads: false
google_analytics:
theme: jekyll-theme-modernist
base_url: /

github:
  repository_url: http://github.com/OpenSeizureDetector
