title: Open Seizure Detector
description: Free, Open Source tools to alert carers if someone suffers an epileptic seizure
show_downloads: false
google_analytics:
baseurl: .

plugins:
  - jekyll-seo-tag

github:
  repository_url: http://github.com/OpenSeizureDetector
