title: Open Seizure Detector
description: Free, Open Source tools to Alert Carers if someone suffers an Epileptic Seizure
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman

defaults:
  - scope:
        path: "assets/img"
      values:
        image: true